# Generated by Django 4.2.7 on 2023-11-21 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
