# Generated by Django 4.2.7 on 2023-11-21 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0002_alter_proveedor_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='imagen',
            field=models.ImageField(blank=True, max_length=250, null=True, upload_to='img', verbose_name='Imagen'),
        ),
    ]
