# Generated by Django 4.2.7 on 2023-11-21 21:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gerencia', '0003_alter_pedido_total'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cliente',
            old_name='baja',
            new_name='baja_cliente',
        ),
    ]
